language: node_js

sudo: false

install:
  - npm install -g babel-cli
  - npm install

node_js:
  - "5.3"
  - "4.2"
  - "0.12"

script: npm test && npm run test_browser

after_script: npm run coveralls
